### ISSUE TITLE
incorrect quote mark

### ISSUE THREAD

**Issue by rsvirk** [raspberrypilearning/getting-started-with-git#11]
Hi in this code:

The above response is telling you that the README.md file has not yet been committed. This means that although Git knows about the file, it doesn't yet have any of the file's contents stored. The simplest way to do a commit is by typing:

git commit -am 'add README.md`

you have used    ->>>  `  <<<<

at the end of the README.md instead of 
>>>> ' <<<<

it gives an error if anyone is cut and pasting and doesnt spot that.

also added a pull request with the fix added.
Thanks 
Rand

**Comment by lawsie** [comment]
Thank you for spotting this, your pull request has been merged. :)
