### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by pvdhyden** [raspberrypilearning/getting-started-with-git#23]
On page https://projects.raspberrypi.org/en/projects/getting-started-with-git, the hyperlink to ... windows... "this guide to install Git shell" (https://projects.raspberrypi.org/en/projects/windows-install.md) does not work. Probably this link should be: https://www.raspberrypi.org/learning/getting-started-with-git/windows-install/.

**Comment by lawsie** [comment]
Cheers @pvdhyden for pointing this out.

@MarcScott This has broken with the port - please could you have a peek?

**Comment by MarcScott** [comment]
Both links now turned into collapsible sections

**Comment by SteveAmor** [comment]
@MarcScott I can't see where both links are now turned into collapsible sections.  Could you reference the PR? :-)

**Comment by lawsie** [comment]
Marc is on leave this week. It looks like he did the work but it hasn't been pulled in from draft. I've sent it for copy edit today so it will be fixed whenever that is done.
