### ISSUE TITLE
Missing quote in python code

### ISSUE THREAD

**Issue by AceTayAimJay** [raspberrypilearning/getting-started-with-git#29]
There is a missing quote in the Python code on worksheet.md
It reads:
```python
printf(Hello World!)
```
and should read:
```python
printf("Hello World!")
```

**Comment by SteveAmor** [comment]
Good spot but it is deliberate.  Also, it reads:

```
print('Hello World!)
```

This missing quote after the `!` is deliberate to teach the student how to create an issue and PR.

**Comment by lawsie** [comment]
:) (Although it's actually print not printf in Python!)
