### ISSUE TITLE
step 10 - sky bag - ssh-key

### ISSUE THREAD

**Issue by hanerlend** [raspberrypilearning/getting-started-with-git#48]
Don't know if this is an issue because I had an old github-account - but I had to generate ssh-keys on my new raspberry pi in order to push to github.

> Permission denied (publickey).

Solution (in Terminal):

`ssh-keygen -t rsa -b 4096 -C "your-email@example.com"`
`eval "$(ssh-agent -s)"`
`ssh-add ~/.ssh/id_rsa`
`sudo apt-get install xclip`
`xclip -sel clip <~/.ssh/id_rsa.pub`

**Comment by MarcScott** [comment]
This is probably because your default was to use ssh when using git. If cloning over https then a username and password are fine.
