### ISSUE TITLE
New typo spotted.

### ISSUE THREAD

**Issue by elliottneyme** [raspberrypilearning/getting-started-with-git#54]
The text reads:

"She can then check through the answers from the whole class in one go. If she spots a mistake, she can write a comment in the margin of the book, and then all the magical bags from the whole class will have receive the comment."

I think it should say, "will receive" and not "will have receive".

**Comment by martinohanlon** [comment]
Thank you resolved with https://github.com/raspberrypilearning/getting-started-with-git/pull/59
