### ISSUE TITLE
getting 403 error trying to push edit

### ISSUE THREAD

**Issue by elliottneyme** [raspberrypilearning/getting-started-with-git#55]
I fetched the repo and made the changes to the file in question.  I can't push the edit though as I'm getting a 403 server error.  Permission is denied.  Some explanation to keep this from happening would be helpful.

**Comment by martinohanlon** [comment]
Could you provide some more information to help me understand where you are experiencing the problem?  A screeenshot or cut and paste of the error would also be useful.

Is it where you are pushing changes to your own repository during the tasks in step 10 - working with a sky bag? https://projects.raspberrypi.org/en/projects/getting-started-with-git/10

Or is it when creating pushing a change so you can created a PR in step 13 https://projects.raspberrypi.org/en/projects/getting-started-with-git/13

Ultimately the error will be the same which is you dont have permission to push the change to the repository. If its in step 13, could it be that you clone the raspberrypilearning repo (https://github.com/raspberrypilearning/getting-started-with-git) and not your own fork of it? (https://github.com/elliottneyme/getting-started-with-git)

**Comment by martinohanlon** [comment]
No response, closing.
