### ISSUE TITLE
Multiple copy-edit errors ('typos') in text

### ISSUE THREAD

**Issue by DeeJay** [raspberrypilearning/getting-started-with-git#6]
"Our copy editors at Raspberry Pi are pretty amazing, so the chances of you spotting a typo in this resource are pretty slim."

Well, there's a challenge...  

Actually, I think there are several, probably unintentional, errors in the body of the text. 

The first is in Section 4, subsection 3: "Next, you can create a file to that will tell people what the project is about."   Either "that will tell people" or "to tell people" would be correct.

Rather than itemize them all here I will use this Resource itself to generate a PR suggesting the fixes required.

But also a genuine question based on my lack of knowledge/experience: In the unnumbered section titled "Pull Requests" it says "head back over to GitHub". Is that the Github repo for the original resource, or is it the Github repo containing the fork in which the modifications have been committed? Clarification would be welcome.

**Comment by DeeJay** [comment]
Following up with some minor observations having worked through the process. 

It seems that the answer to my query about which repo to raise the PR from is that it is the submitter's own fork of the repo that is used. I'm happy to generate a clarification PR to this effect if someone can confirm I've got it right?

I notice that the major section headings for 'Pull requests' and 'What next?' are not automatically numbered. I don't see any difference in the MD markup for these sections that would make them differ from earlier such headings. Maybe MD has a built-in limit of 10 such ## sections?

**Comment by MarcScott** [comment]
Thank you - you pull has been submitted to copy edit.
Yes, you are correct that the pull is generated from the submitters fork - happy for you to submit another pull request on this.
Numbering breaks after 10. I should split this worksheet, but not urgent.
Cheers
