### ISSUE TITLE
questions about git

### ISSUE THREAD

**Issue by albertcamin** [raspberrypilearning/getting-started-with-git#60]
Hello! I'm starting to use Git hub. I followed the Raspberry instructions to share a code in Github, but when I wanted to do "remote add origin git@github.com...", something failed and the repo is added in the web page of my account in github, but  neiher in the desktop github, nor in the Atom, nor can access anymore through Git Bash. The  mistake message says in Atom: "Unable to push.. Permision denied (publickey). fatal:could not read from remote repository. Please make sure  that you have the correct access rights and the repository exists". 
Someone could please help me?

**Comment by MarcScott** [comment]
Atom and the GitHub app use different authentication methods, I think. You'll have to look at their documentation. Sorry I can't be more help. I only really use git through the terminal.
